project:
  type: book
  output-dir: docs

book:
  title: "R and Quarto"
  subtitle: "Creating Interactive Data Analysis Reports/Books/Manuscripts"
  author: "Liberty Mlambo"
  date: "10/01/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - custom_page.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



